apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: vol-printer
      image: busybox:1.34.1
      command:
        - /bin/sh
        - -c
        - "sleep 99d"
      volumeMounts:
        - name: my-volume
          mountPath: /opt/my-volume
  volumes:
    - name: my-volume
      secret:
        secretName: a-secret