apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    type: my-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/my-pv"